[tool.poetry]
name = "rmq_py_caller"
version = "0.1.0"
description = ""
authors = ["Will Badart <badart_william@bah.com>"]

[tool.poetry.dependencies]
python = "^3.8"
jq = "^1.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
