version: "3.4"
services:
  fish_prediction:
    build: .
    image: fish_prediction
    environment:
      PY_SETUP: "from rmq_sklearn.predict import setup_inference"
      PY_TARGET: "setup_inference(path='/models/tree.joblib')"
      # Note the double '$' to prevent docker-compose from doing variable substitution
      OUTPUT_ADAPTER: >-
        .orig as $$orig | .result as $$result |
        [ range(.result | length) | . as $$i |
            $$orig[$$i] * { Prediction: $$result[$$i] }
            ]
      INPUT_QUEUE: "data_in"
      OUTPUT_EXCHANGE: "data_out"
      RABTAP_AMQPURI: "amqp://guest:guest@host.docker.internal:5672/"
    volumes:
    - ${PWD}/tree.joblib:/models/tree.joblib
